name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code to specific branch
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2

      - name: Run Tests
        run: ./gradlew test

      - name: Build Project
        run: ./gradlew assemble

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Generate app bundle.
        run: ./gradlew app:bundleRelease --stacktrace

      - name: Generate app APK.
        run: ./gradlew assembleRelease --stacktrace

      - name: Sign app bundle
        run: |
          jarsigner -keystore app/*.jks \
          -storepass ${{ secrets.KEY_STORE_PASSWORD }} -keypass ${{ secrets.KEY_PASSWORD }} \
          app/build/outputs/bundle/release/app-release.aab ${{ secrets.ALIAS }}  
